version: "2"
services:
  satis:
    image: ealebed/satis:latest
    restart: always
    container_name: satis
    hostname: satis
    volumes:
      - "./COMPOSER_CACHE:/root/.composer"
      - "./satis.json:/app/config.json"
      - "./dist:/satisfy/web/dist"
      - "./include:/satisfy/web/include"
    environment:
      CRONTAB_FREQUENCY: "*/10 * * * *"
      VIRTUAL_HOST: satis.lc
    ports:
      - 3333:3000
      - 8181:80
